### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by wakaka123wakaka** [chroblert/JCRandomProxy#2]
![image](https://user-images.githubusercontent.com/34087959/95564270-212a9680-0a51-11eb-82fd-953809e815af.png)

**Comment by wakaka123wakaka** [comment]
![image](https://user-images.githubusercontent.com/34087959/95566733-8d5ac980-0a54-11eb-9147-424001a0004c.png)

**Comment by chroblert** [comment]
将liblcl.dll文件拷贝到windows/system32目录下
