### ISSUE TITLE
log.txt生成量巨大，五个小时就生成了超过10g以上的日志量

### ISSUE THREAD

**Issue by wakaka123wakaka** [chroblert/JCRandomProxy#3]
![image](https://user-images.githubusercontent.com/34087959/95656543-ac835500-0b41-11eb-876b-550ace951456.png)
我删除过一次，还是很快的生成这么多

**Comment by chroblert** [comment]
https://github.com/chroblert/JCRandomProxy/releases/tag/v3.1
优化了日志模块，3.1版，可以配置日志的大小、个数以及保存时间
