### ISSUE TITLE
修改配置文件后，没读取配置文件中的内容

### ISSUE THREAD

**Issue by ymbzd** [chroblert/JCRandomProxy#4]
修改了配置文件测试网络连接性的URL，未读取配置文件中的内容

**Comment by chroblert** [comment]
1.是否使用了3.1版的程序
2. config.ini文件是否放在exe的同级目录Conf下
3.是否有截图

**Comment by ymbzd** [comment]
是3.1，也在conf目录下
![image](https://user-images.githubusercontent.com/39881690/96969105-851a8800-1544-11eb-8201-ba39ff0dfb23.png)

**Comment by chroblert** [comment]
![image](https://user-images.githubusercontent.com/24365224/97150112-9fed3680-17a8-11eb-866f-42cb09a5cfaf.png)

经检查，原因是没有对CheckProxy下的内容进行读取，

**Comment by chroblert** [comment]
测试代理有效性的URL是有一些要求的：
响应内容中包含代理IP，则表示该代理有效；否则无效

**Comment by ymbzd** [comment]
建议再添加一个测试连通性的URL，可以在界面中自己填写reponse返回的内容来判断是否代理成功，方便对指定目标选择有效代理~另外希望优化UI，在2K的分辨率下看起来太奇怪啦，感谢大佬的工具，希望可以更完美

**Comment by chroblert** [comment]
已增加：
ProxyCheckAddr：自定义校验的URL
CustomSucFlag：自定义成功时返回的内容。默认为false，表示代理IP在响应body中则有效。若修改，则使用自定义内容作为校验成功的标志。
