### ISSUE TITLE
mac使用问题

### ISSUE THREAD

**Issue by godzeo** [chroblert/JCRandomProxy#6]
go的不太懂，windows的可以运行，但是像mac上直接用，但是运行不行了，用的命令行版本的报错，mac可以编译gui吗？

![image](https://user-images.githubusercontent.com/64398024/101117278-9d8cc080-3621-11eb-9960-7d008f973be2.png)

**Comment by aiwennba** [comment]
> go的不太懂，windows的可以运行，但是像mac上直接用，但是运行不行了，用的命令行版本的报错，mac可以编译gui吗？
> 
> ![image](https://user-images.githubusercontent.com/64398024/101117278-9d8cc080-3621-11eb-9960-7d008f973be2.png)

mac 的go版本太高gui编译不成功不过我已经改成无界面版本，mac 和linux 完美运行~！

**Comment by chroblert** [comment]
我这边没有mac的环境，可以clone GUIVersion分支的最新代码
使用如下命令编译：
```shell
go build .
```
